[project]
name = "aim-hot-mess-coach"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "uvicorn>=0.38.0",
    "python-multipart>=0.0.9",
    "openai>=2.9.0",
    "dotenv>=0.9.9",
]
